### ISSUE TITLE
1.12.2 Air cannot be cast to net.minecraft.item.itemblock

### ISSUE THREAD

**Issue by DatrixTHLK** [2piradians/Block-Armor#23] opened 2018-09-01 18:24 UTC
Hi,

Crashed while trying to startup Minecraft. Not sure why air would be part of the block armor. Most likely unintended. Thanks for at least taking a look at this.

Minecraft: 1.12.2
forge: 14.23.4.2759
BlockArmor: 2.4.11

Crash Log: https://gist.github.com/DatrixTHLK/d87fc7cbe9ced24167ee6e33abcbfadd

**Comment by 2piradians** [comment] 2018-09-02 07:42
Based on how many mods there are installed and how few times this happens, I would assume the issue is caused by another mod not playing nice with Block Armor. I see SpongeForge listed at some point in the log. I would start with removing that and restarting. If not, then remove mods until it loads. You will likely find the mod, and you can disable armor from that mod and should have no issues loading up afterwards.

**Comment by DatrixTHLK** [comment] 2018-09-02 12:54
Well, problem is, I was told by VanillaFix that this mod most likely caused the issue. Thanks for the response.

**Comment by 2piradians** [comment] 2018-09-02 13:08
You were told correctly for the direct cause of the crash. However, the issue isn't just one mod (we would see these crashes way more often if Block Armor was screwing up alone). It's likely the compatibility between Block Armor and another mod, due to how Block Armor creates armor at startup from another mod's textures. You could disable generating modded block armors, if you prefer just having vanilla block armor, and then you should no longer have an issue. Otherwise, to keep most modded armors, you will need to find the mods that our mod is having issues with.

**Comment by NoahJelen** [comment] 2019-05-09 01:58
I got this issue trying to use this mod with the latest version of quark

**Comment by Furgl** [comment] 2020-08-31 22:28
Fixed in v2.4.12

**Closed as completed by Furgl** 2020-08-31 22:28 UTC
