### ISSUE TITLE
untextured armor crash

### ISSUE THREAD

**Issue by superon** [2piradians/Block-Armor#7] opened 2017-05-07 10:24 UTC
seems a lot of the armour from this mod crashes the client, not sure why this is or how to fix the issue but i have found the login in through bootcamp/windows (running macOS here) will allow me to view these items without resulting in a crash...     other people are not so fortunate, everyone else that has attempted to view a piece of armor (placed in a chest now) has crashed with a similar sounding render error... https://pastebin.com/zj5YvnKa
also just a small note to say that i've been resolving this for other players so far by killing them if they have get one of these items in they inventories so i can "fix" it in that sense ;)

**Comment by 2piradians** [comment] 2017-05-07 15:17
The crash report does not directly suggest Block Armor is the issue, so could you provide more information? Is it any armor piece that shows the purple/black no texture in the inventory? Is everyone else with this issue on Mac? It appears you are using the Foolcraft modpack; what armors in the modpack are causing the issue? We have played the modpack and have yet to encounter any issue, so it would help if you could direct us to the specific armors causing your issue.

You could disable the problematic armor sets in server config, and then they will no longer be available to cause issue.

**Comment by 2piradians** [comment] 2017-05-13 00:27
Insufficient information given for issue to be reproduced. Closing issue until such information can be provided or issue is confirmed to exist.

**Closed as completed by 2piradians** 2017-05-13 00:27 UTC

**Comment by superon** [comment] 2017-06-02 16:24
sorry about lack of info on this, been about impossible to gather, here's what i know now.  the armors that produce the crash will crash certain people but not all people.
yes it appears to be every kind that looks untextured.
i've asked others that use windows and they either do or don't crash, not pattern there.
none else i'm playing with runs mac.
i am playing with the foolcraft pack
i managed to log in with windows and didn't crash so used bootcamp to put the items away safely.
i did consider disabling the armour sets that was causing the issue but that is almost improbably difficult when the amours firstly don't even appear in jei, thirdly only appear with the illuminati pet (as they're actually uncraftable in the pack) and thirdly are only discovered when they crash the client...   once you add all the numbers together we decided the simplest (and mosdef quickest) solution was to disable blockarmor

**Comment by Furgl** [comment] 2017-06-02 17:27
Knowing that these untextured armors are only coming from the Illuminati pet makes a lot more sense. 

Long explanation:
The way that Block Armor works is that it first searches through all blocks registered in the game and picks blocks that meet certain criteria (full blocks, not blacklisted, etc.) and creates armor items for these blocks on both client and server. Then, when the client connects to a server, the client attempts to map the block textures to the armor, since this can only be done on the client at runtime. Some of the blocks have textures mapped in unique, unconventional ways (via custom renderer or otherwise) that makes it difficult/impossible to map the blocks' textures systematically; this results in armor sets without textures. Our code then sees that the armor items have no textures and disables the armor set in the config so the items will have no recipe and are removed from creative tabs and JEI. 
The Block Armor config also has an option, set to false by default in Foolcraft, to register disabled items. Because this is false in Foolcraft, items that are disabled in the config (i.e. armor sets with missing textures) are not registered by the client, but are still registered on the server (remember that these sets are only disabled on the client and not the server). Normally this is fine: disabled items cannot be crafted by the client, they're not in JEI or creative tabs, and there's no direct way to spawn them in. 
Unfortunately, the Illuminati pet spawns in random items. So what's happening is that the Illuminati pet is spawning in armor items that are enabled on the server, but disabled on the client (because of missing textures); these disabled items aren't registered with the client, so the game crashes. 

Probable solutions:
1. The Illuminati pet does have an item blacklist, but it would take a long time to add all items with missing textures to it. The simplest solution would be to just disable the Illuminati pet in the config. This would stop the untextured items from being spawned in.
2. Another solution would be to set the config option "Register disabled items" to true on the clients. This will allow the clients to register all Block Armor items, including disabled items (which may use a bit more memory in a large modpack like Foolcraft). This will make it so the client will recognize the untextured items and not crash when seeing one. 
Note: if you decide to change this option in the server's config, it will sync to the client config of any client that connects to the server, as you would want, but it will not take effect until that client restarts Minecraft again (as items can only be registered when Minecraft is starting up).
